---
deployment:
  tasks:
    - export DEPLOYPATH=/home/nrgwgarn/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp 404.html $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp discord.html $DEPLOYPATH
    - /bin/cp setup.html $DEPLOYPATH
    - /bin/cp social.html $DEPLOYPATH
    - /bin/cp /css/* $DEPLOYPATH
    - /bin/cp /guides/* $DEPLOYPATH
    - /bin/cp /guides/index.html $DEPLOYPATH
    - /bin/cp /images/* $DEPLOYPATH
    - /bin/cp /js/* $DEPLOYPATH
    - /bin/cp /libs/* $DEPLOYPATH